### ISSUE TITLE
Severe issue with latest dev build 1.4.5-R0.3 and DtlCitizensTrader v2.0.0

### ISSUE THREAD

**Issue by Jemrada** [Dandielo/DtlCitizensTrader#20]
15:13:42 [SEVERE] net/minecraft/server/NBTBase initializing DtlCitizensTrader v2.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/NBTBase
        at net.dtl.citizens.trader.CitizensTrader.onLoad(CitizensTrader.java:67)
        at org.bukkit.craftbukkit.v1_4_5.CraftServer.loadPlugins(CraftServer.java:232)
        at org.bukkit.craftbukkit.v1_4_5.CraftServer.<init>(CraftServer.java:205)
        at net.minecraft.server.v1_4_5.ServerConfigurationManagerAbstract.<init>(ServerConfigurationManagerAbstract.java:51)
        at net.minecraft.server.v1_4_5.ServerConfigurationManager.<init>(SourceFile:11)
        at net.minecraft.server.v1_4_5.DedicatedServer.init(DedicatedServer.java:111)
        at net.minecraft.server.v1_4_5.MinecraftServer.run(MinecraftServer.java:398)
        at net.minecraft.server.v1_4_5.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.NBTBase
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:34)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 8 more

**Comment by Jemrada** [comment]
Also, I see this in console

15:27:32 [SEVERE] Error occurred while enabling DtlCitizensTrader v2.0.0 (Is it up to date?)
java.lang.NullPointerException
        at net.dtl.citizens.trader.CitizensTrader.info(CitizensTrader.java:281)
        at net.dtl.citizens.trader.CitizensTrader.onEnable(CitizensTrader.java:86)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.v1_4_5.CraftServer.loadPlugin(CraftServer.java:270)
        at org.bukkit.craftbukkit.v1_4_5.CraftServer.enablePlugins(CraftServer.java:252)
        at net.minecraft.server.v1_4_5.MinecraftServer.j(MinecraftServer.java:320)
        at net.minecraft.server.v1_4_5.MinecraftServer.e(MinecraftServer.java:299)
        at net.minecraft.server.v1_4_5.MinecraftServer.a(MinecraftServer.java:258)
        at net.minecraft.server.v1_4_5.DedicatedServer.init(DedicatedServer.java:147)
        at net.minecraft.server.v1_4_5.MinecraftServer.run(MinecraftServer.java:398)
        at net.minecraft.server.v1_4_5.ThreadServerApplication.run(SourceFile:856)

**Comment by Dandielo** [comment]
Looks like Bukkit has removed some functions from the API or has changed their names or visibility. Going to check that

**Comment by Dandielo** [comment]
Plugin was updated to match bukkit 1.4.5-R0.3 
you can download it here from download tab

**Comment by Jemrada** [comment]
I still getting a error from the new build.

16:03:01 [SEVERE] Error occurred while enabling DtlCitizensTrader v2.1.0 Beta (Is it up to date?)
java.lang.NoClassDefFoundError: net/aufdemrand/denizen/commands/AbstractCommand
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:44)
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:238)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:40)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at net.dtl.citizens.trader.CitizensTrader.initializeDenizenCommands(CitizensTrader.java:198)
        at net.dtl.citizens.trader.CitizensTrader.onEnable(CitizensTrader.java:151)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.v1_4_5.CraftServer.loadPlugin(CraftServer.java:270)
        at org.bukkit.craftbukkit.v1_4_5.CraftServer.enablePlugins(CraftServer.java:252)
        at net.minecraft.server.v1_4_5.MinecraftServer.j(MinecraftServer.java:320)
        at net.minecraft.server.v1_4_5.MinecraftServer.e(MinecraftServer.java:299)
        at net.minecraft.server.v1_4_5.MinecraftServer.a(MinecraftServer.java:258)
        at net.minecraft.server.v1_4_5.DedicatedServer.init(DedicatedServer.java:147)
        at net.minecraft.server.v1_4_5.MinecraftServer.run(MinecraftServer.java:398)
        at net.minecraft.server.v1_4_5.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.denizen.commands.AbstractCommand
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:44)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 28 more

**Comment by Dandielo** [comment]
you got denizens ?

**Comment by Dandielo** [comment]
Ok i can make it work but atm without denizens support so no triggers and commands, because it looks like Aufdemrand just changed the API ^^

**Comment by Jemrada** [comment]
Yes

**Comment by Dandielo** [comment]
available for download

**Comment by Jemrada** [comment]
Ok, I only use it for a trader right now anyways. So maybe it will be ok.

Not sure if I should still see an error or not in console. I get this still.

16:25:45 [SEVERE] Error occurred while enabling DtlCitizensTrader v2.1.0 Beta (Is it up to date?)
java.lang.NoClassDefFoundError: net/aufdemrand/denizen/commands/AbstractCommand
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.security.SecureClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.defineClass(Unknown Source)
        at java.net.URLClassLoader.access$100(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:44)
        at org.bukkit.plugin.java.JavaPluginLoader.getClassByName(JavaPluginLoader.java:238)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:40)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at net.dtl.citizens.trader.CitizensTrader.initializeDenizenCommands(CitizensTrader.java:198)
        at net.dtl.citizens.trader.CitizensTrader.onEnable(CitizensTrader.java:151)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.v1_4_5.CraftServer.loadPlugin(CraftServer.java:270)
        at org.bukkit.craftbukkit.v1_4_5.CraftServer.enablePlugins(CraftServer.java:252)
        at net.minecraft.server.v1_4_5.MinecraftServer.j(MinecraftServer.java:320)
        at net.minecraft.server.v1_4_5.MinecraftServer.e(MinecraftServer.java:299)
        at net.minecraft.server.v1_4_5.MinecraftServer.a(MinecraftServer.java:258)
        at net.minecraft.server.v1_4_5.DedicatedServer.init(DedicatedServer.java:147)
        at net.minecraft.server.v1_4_5.MinecraftServer.run(MinecraftServer.java:398)
        at net.minecraft.server.v1_4_5.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.denizen.commands.AbstractCommand
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.net.URLClassLoader$1.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(Unknown Source)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:44)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 28 more

**Comment by Dandielo** [comment]
ah yeah forgot to clear 1 more method

if this one won't work the you will need to wait until I'm ready with a bit more stable beta build

**Comment by Jemrada** [comment]
Nope that didn't do it. Trader not working ether. I appreciate your promptness in trying to get this fixed. I look forward to your next release.

**Comment by Dandielo** [comment]
sorry for that :/ it will take some time tbh, cose working atm on bankers too so, code was a bit messed up. Will do my best to fix this fast
