### ISSUE TITLE
Error on last build and last Bukkit

### ISSUE THREAD

**Issue by cranic** [Dandielo/DtlCitizensTrader#24]
I used the last dev build of Bukkit.

```
14:58:20 [SEVERE] Error occurred while enabling DtlCitizensTrader v2.1.1 Beta (Is it up to date?)
java.lang.NullPointerException
at net.dtl.citizens.trader.CitizensTrader.info(CitizensTrader.java:309)
    at net.dtl.citizens.trader.CitizensTrader.onEnable(CitizensTrader.java:95)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:374)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_4_5.CraftServer.loadPlugin(CraftServer.java:304)
    at org.bukkit.craftbukkit.v1_4_5.CraftServer.enablePlugins(CraftServer.java:286)
    at net.minecraft.server.v1_4_5.MinecraftServer.j(MinecraftServer.java:324)
    at net.minecraft.server.v1_4_5.MinecraftServer.e(MinecraftServer.java:303)
    at net.minecraft.server.v1_4_5.MinecraftServer.a(MinecraftServer.java:262)
    at net.minecraft.server.v1_4_5.DedicatedServer.init(DedicatedServer.java:147)
    at net.minecraft.server.v1_4_5.MinecraftServer.run(MinecraftServer.java:402)
    at net.minecraft.server.v1_4_5.ThreadServerApplication.run(SourceFile:856)
```

**Comment by Dandielo** [comment]
This build is not for Alpha/Beta 1.4.5-R0.3

**Comment by cranic** [comment]
Was Citizens build did you used? I'm having trouble to find a build that workd with 1.4.5R02

**Comment by Dandielo** [comment]
Trader version for bukkit 1.4.5-R1.0 was uploaded today on dev.bukkit.org. We need just to wait for approval :)
