### ISSUE TITLE
Error when selling and selecting NPCs

### ISSUE THREAD

**Issue by cranic** [Dandielo/DtlCitizensTrader#25]
Hey there. I'm getting "Not enought money" when I try to sell something to the NPC, and when I select the NPC with a stick and type "/trader", I get this error:

```
2012-12-20 14:57:02 [INFO] alan issued server command: /trader
2012-12-20 14:57:02 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'trader' in plugin DtlCitizensTrader v2.2.0 Beta
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
    at org.bukkit.craftbukkit.v1_4_5.CraftServer.dispatchCommand(CraftServer.java:539)
    at net.minecraft.server.v1_4_5.NetServerHandler.handleCommand(NetServerHandler.java:999)
    at net.minecraft.server.v1_4_5.NetServerHandler.chat(NetServerHandler.java:917)
    at net.minecraft.server.v1_4_5.NetServerHandler.a(NetServerHandler.java:861)
    at net.minecraft.server.v1_4_5.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.v1_4_5.NetworkManager.b(NetworkManager.java:290)
    at net.minecraft.server.v1_4_5.NetServerHandler.d(NetServerHandler.java:113)
    at net.minecraft.server.v1_4_5.ServerConnection.b(SourceFile:39)
    at net.minecraft.server.v1_4_5.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.v1_4_5.MinecraftServer.r(MinecraftServer.java:584)
    at net.minecraft.server.v1_4_5.DedicatedServer.r(DedicatedServer.java:222)
    at net.minecraft.server.v1_4_5.MinecraftServer.q(MinecraftServer.java:480)
    at net.minecraft.server.v1_4_5.MinecraftServer.run(MinecraftServer.java:415)
    at net.minecraft.server.v1_4_5.ThreadServerApplication.run(SourceFile:856)
Caused by: java.lang.NullPointerException
    at net.dtl.citizens.trader.TraderCommandExecutor.onCommand(TraderCommandExecutor.java:82)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
    ... 15 more
```

**Comment by Dandielo** [comment]
fixed
