### ISSUE TITLE
Banker types

### ISSUE THREAD

**Issue by Dandielo** [Dandielo/DtlCitizensTrader#36]
Finish the bankers so they can be used on servers

**Comment by draxum** [comment]
I updated Citizens 2  v2.0.7 and installed the new DtlTrader to set up bankers.  When I use the /banker to get the commands I get the following error on the server.

08:52:56 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'banker' in plugin DtlCitizensTrader v2.4.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46)
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:186)
        at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServer.java:514)
        at net.minecraft.server.v1_4_R1.PlayerConnection.handleCommand(PlayerConnection.java:979)
        at net.minecraft.server.v1_4_R1.PlayerConnection.chat(PlayerConnection.java:897)
        at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java:852)
        at net.minecraft.server.v1_4_R1.Packet3Chat.handle(Packet3Chat.java:44)
        at net.minecraft.server.v1_4_R1.NetworkManager.b(NetworkManager.java:290)
        at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java:112)
        at net.minecraft.server.v1_4_R1.ServerConnection.b(SourceFile:39)
        at net.minecraft.server.v1_4_R1.DedicatedServerConnection.b(SourceFile:30)
        at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:598)
        at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224)
        at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)
        at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)
        at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0        at net.dtl.citizens.trader.BankerCommandExecutor.onCommand(BankerCommand
Executor.java:47)        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
        ... 15 more

**Comment by Dandielo** [comment]
going to fix as fast as I can

**Comment by Dandielo** [comment]
ok banker commands ane most messages are fixed with the latest build :) 
atm there are only 3 commands to use, all other will come in time

/banker create Banker name t:type e:entity 
/banker reload
/banker

**Comment by draxum** [comment]
Thanks for the update, I downloaded the mod and was able to successfully create a Banker.  When you click on him he does open up a area like a double chest but I can not place anything in it.  I can not move items in my inventory area also.  I have downloaded the latest version of Citizens 2 but do I need the API to use the Banker Plugin?  I am set up as owner of the server in permission as I have given myself dtl.banker.*.  I also deleted the old Dtltrader folder and restarted the server to allow it to create a new folder.  Is there anything that I am forgetting that may be causing this?

**Comment by Dandielo** [comment]
Nah that shouldn't happen hmm... I'm going to check some permission setups

**Comment by Dandielo** [comment]
Sorry i looks like there was a small bug with that version and the banker command created a trader dunno why, anyway try the latest build. If you will see 1 small wool on the left bottom corner then it's a banker :)

**Comment by draxum** [comment]
Worked beautifully!

**Comment by Dandielo** [comment]
So i can close this issue :) Thanks for feedback :) Any ideas are welcome :D
