### ISSUE TITLE
Some items prevent users rightclick on traders

### ISSUE THREAD

**Issue by Rob-bb** [Dandielo/DtlCitizensTrader#46]
Hi

When one of my players holds the item "Shard of Minium" from ee3 mod they can nopt talk to traders, and this error gets dumped to the log.

When they drop the item all is good again.

Cheers,

2013-02-27 13:40:14 [SEVERE] Could not pass event NPCRightClickEvent to DtlCitizensTrader v2.2.5
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:341)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.citizensnpcs.EventListen.onPlayerInteractEntity(EventListen.java:226)
    at sun.reflect.GeneratedMethodAccessor98.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.minecraft.server.v1_4_6.PlayerConnection.a(PlayerConnection.java:1129)
    at net.minecraft.server.v1_4_6.Packet7UseEntity.handle(SourceFile:36)
    at net.minecraft.server.v1_4_6.NetworkManager.b(NetworkManager.java:291)
    at net.minecraft.server.v1_4_6.PlayerConnection.d(PlayerConnection.java:122)
    at net.minecraft.server.v1_4_6.ServerConnection.b(ServerConnection.java:54)
    at net.minecraft.server.v1_4_6.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.v1_4_6.MinecraftServer.r(MinecraftServer.java:629)
    at net.minecraft.server.v1_4_6.DedicatedServer.r(DedicatedServer.java:228)
    at net.minecraft.server.v1_4_6.MinecraftServer.q(MinecraftServer.java:517)
    at net.minecraft.server.v1_4_6.MinecraftServer.run(MinecraftServer.java:447)
    at net.minecraft.server.v1_4_6.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 624
    at org.bukkit.craftbukkit.v1_4_6.inventory.CraftItemFactory.getItemMeta(CraftItemFactory.java:48)
    at org.bukkit.craftbukkit.v1_4_6.inventory.CraftItemFactory.getItemMeta(CraftItemFactory.java:44)
    at org.bukkit.craftbukkit.v1_4_6.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:303)
    at org.bukkit.craftbukkit.v1_4_6.inventory.CraftItemStack.getItemMeta(CraftItemStack.java:298)
    at org.bukkit.inventory.ItemStack.serialize(ItemStack.java:481)
    at net.dtl.citizens.trader.objects.NBTTagEditor.removeDescriptions(NBTTagEditor.java:33)
    at net.dtl.citizens.trader.types.ServerTrader.onRightClick(ServerTrader.java:969)
    at net.dtl.citizens.trader.NpcEcoManager.onNPCRightCLick(NpcEcoManager.java:307)
    at sun.reflect.GeneratedMethodAccessor101.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:601)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:339)
    ... 22 more

**Comment by Dandielo** [comment]
Working on it, but it might take some time

**Comment by Rob-bb** [comment]
All good.  I only have about 6 players, my kids and some of their friends,  so have told what to do when buying.

**Comment by Dandielo** [comment]
I was looking into it, may you try the latest build and tell me if this still happens?

**Comment by Rob-bb** [comment]
Unfortunately I am stuck running an mpcp 1.4.6 server.  If I upgrade to the 1.4.7 I would have to replace all the plugins and that will have to wait for a while.  My players know the work around and now you know about the issue it's hopefully fixed for other people.   Thanks
