### ISSUE TITLE
[Bug] Error with 

### ISSUE THREAD

**Issue by spaceemotion** [Dandielo/DtlCitizensTrader#56]
Got this with latest Denizen Dev-Build (I want to test the features! ;D):

```
09:56:09 [SEVERE] Error occurred while enabling DtlCitizensTrader v2.5.0 Alpha (Is it up to date?)
java.lang.NoSuchMethodError: net.aufdemrand.denizen.scripts.triggers.AbstractTrigger.withOptions(ZDLnet/aufdemrand/denizen/scripts/triggers/TriggerRegistry$CooldownType;)Lnet/aufdemrand/denizen/scripts/triggers/AbstractTrigger;
    at net.dandielo.citizens.trader.denizen.AbstractDenizenTrigger.registerTriggers(AbstractDenizenTrigger.java:13)
    at net.dandielo.citizens.trader.CitizensTrader.initializeDenizens(CitizensTrader.java:197)
    at net.dandielo.citizens.trader.CitizensTrader.onEnable(CitizensTrader.java:162)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.loadPlugin(CraftServer.java:304)
    at org.bukkit.craftbukkit.v1_4_R1.CraftServer.enablePlugins(CraftServer.java:286)
    at net.minecraft.server.v1_4_R1.MinecraftServer.j(MinecraftServer.java:327)
    at net.minecraft.server.v1_4_R1.MinecraftServer.e(MinecraftServer.java:306)
    at net.minecraft.server.v1_4_R1.MinecraftServer.a(MinecraftServer.java:265)
    at net.minecraft.server.v1_4_R1.DedicatedServer.init(DedicatedServer.java:153)
    at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:405)
    at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)

```

**Comment by Dandielo** [comment]
Fixed
