### ISSUE TITLE
[Bug] Don't work anymore

### ISSUE THREAD

**Issue by marcosds13** [Dandielo/DtlCitizensTrader#57]
The DtlTraders dont work anymore in my server.
In past worked fine

give this error in version 2.4.0 and 2.4.3 with Recommeded Build of Craftbukkit:
18:11:31 [SEVERE] Error occurred while enabling DtlCitizensTrader v2.4.3 (Is it
up to date?)
java.lang.NullPointerException
at net.dandielo.citizens.trader.CitizensTrader.info(CitizensTrader.java:
267)
at net.dandielo.citizens.trader.CitizensTrader.onEnable(CitizensTrader.j
ava:81)
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader
.java:457)
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManage
r.java:381)
at net.skycraftmc.PluginManager.PluginManagerPlugin.onCommand(PluginMana
gerPlugin.java:208)
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:18
6)
at org.bukkit.craftbukkit.v1_4_R1.CraftServer.dispatchCommand(CraftServe
r.java:514)
at net.minecraft.server.v1_4_R1.PlayerConnection.handleCommand(PlayerCon
nection.java:980)
at net.minecraft.server.v1_4_R1.PlayerConnection.chat(PlayerConnection.j
ava:898)
at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java
:853)
at net.minecraft.server.v1_4_R1.Packet3Chat.handle(Packet3Chat.java:44)
at net.minecraft.server.v1_4_R1.NetworkManager.b(NetworkManager.java:290
)
at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java
:113)
at net.minecraft.server.v1_4_R1.ServerConnection.b(SourceFile:39)
at net.minecraft.server.v1_4_R1.DedicatedServerConnection.b(SourceFile:3
0)
at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:5
98)
at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:2
24)
at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:4
94)
at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java
:427)
at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:8
49)

**Comment by Dandielo** [comment]
Try the latest 2.5
