### ISSUE TITLE
AND AGAIN

### ISSUE THREAD

**Issue by FluiD96** [Dandielo/DtlCitizensTrader#6]
Some new issues by me.
For a first, creating trader with /trader create - crushing server now :D IT'S SOOOOO NICE!
For a second, it's something wrong with managing mode, I CAN'T ADD NEW STOCK ITEM'S!!
And yes, now it saving price's thanks.

**Comment by FluiD96** [comment]
And I forgot, it still creating trader with /npc create _npc name_ --trait trader

**Comment by Dandielo** [comment]
1. send me a template command that crashes the server (send me Citizens and Bukkit and if you got Denizen version you'r using)

**Comment by Dandielo** [comment]
2 how does this problem looks like? do it say Sth CReative mode?)

**Comment by FluiD96** [comment]
First command that crashes sever - /trader create, and every similar cmd like /trader create _tradername_ -t:player -o:owner e.t.c. DtlTraders ver. 1.961 , Citizens (TRYED VER.) 2.01 ,2.03, Denizen ver 0.76 dev. on DtlTraders ver 1.96 anything work pretty nice.

Second - normal mode, using a stick enter managing mode, after thst go in trader stock, pressing on any item in my inventory annnnd , it's nothing, thats just pick an item, if I try to drop item in trader stock I'll lose an item, but item would not be added. FIX that please.

And logs from bukkit.

Darkside использовал серверную команду: /trader create t:player o:Darkside
2012-10-20 10:59:32 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'trader' in plugin DtlCitizensTrader v1.9.61Beta
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:601)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:880)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:826)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:808)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:124)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:276)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at org.getspout.spout.SpoutNetServerHandler.d(SpoutNetServerHandler.java:203)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:605)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:245)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:501)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(Unknown Source)
    at net.dtl.citizens.trader.TraderCommandExecutor.createTrader(TraderCommandExecutor.java:834)
    at net.dtl.citizens.trader.TraderCommandExecutor.onCommand(TraderCommandExecutor.java:108)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)
    ... 17 more
2012-10-20 11:00:07 [INFO] Darkside использовал серверную команду: /trader create
2012-10-20 11:00:07 [SEVERE] null
org.bukkit.command.CommandException: Unhandled exception executing command 'trader' in plugin DtlCitizensTrader v1.9.61Beta
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:42)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:601)
    at net.minecraft.server.NetServerHandler.handleCommand(NetServerHandler.java:880)
    at net.minecraft.server.NetServerHandler.chat(NetServerHandler.java:826)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:808)
    at org.getspout.spout.SpoutNetServerHandler.a(SpoutNetServerHandler.java:124)
    at net.minecraft.server.Packet3Chat.handle(Packet3Chat.java:44)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:276)
    at net.minecraft.server.NetServerHandler.d(NetServerHandler.java:109)
    at org.getspout.spout.SpoutNetServerHandler.d(SpoutNetServerHandler.java:203)
    at net.minecraft.server.ServerConnection.b(SourceFile:35)
    at net.minecraft.server.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.MinecraftServer.q(MinecraftServer.java:605)
    at net.minecraft.server.DedicatedServer.q(DedicatedServer.java:245)
    at net.minecraft.server.MinecraftServer.p(MinecraftServer.java:501)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:419)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:539)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
    at java.lang.String.substring(Unknown Source)
    at net.dtl.citizens.trader.TraderCommandExecutor.createTrader(TraderCommandExecutor.java:834)
    at net.dtl.citizens.trader.TraderCommandExecutor.onCommand(TraderCommandExecutor.java:108)
    at org.bukkit.command.PluginCommand.execute(PluginCommand.java:40)

**Comment by Dandielo** [comment]
"/trader create" is fixed alredy in my code, moreover found two additional bugs fixing that one
i will add a developement release here on github, so if you want you can be a tester and look out for bugs ;>

**Comment by FluiD96** [comment]
Okay, I'll do that, anyway, i like that plugin and need it for my server, it's much comfortable to use it than Chestshop. And PM me where is development release ,I'll check it out...

**Comment by Dandielo** [comment]
ok a fixed version is for downlaod available on this page
