### ISSUE TITLE
Error when trying to convert from cititraders

### ISSUE THREAD

**Issue by mozartripper** [Dandielo/DtlCitizensTrader#61]
this is the error I get when I add
    cititrader:
        convert: true
to the config.
2013-03-23 16:57:57 [INFO] [DtlCitizensTrader] Enabling DtlCitizensTrader v2.5.0 Alpha
2013-03-23 16:57:57 [INFO] [DtlCitizensTrader] [0;37;1mLoading locale[m
2013-03-23 16:57:57 [SEVERE] Error occurred while enabling DtlCitizensTrader v2.5.0 Alpha (Is it up to date?)
java.lang.NullPointerException
    at net.dandielo.citizens.trader.ItemsConfig.convertStringData(ItemsConfig.java:87)
    at net.dandielo.citizens.trader.ItemsConfig.<init>(ItemsConfig.java:47)
    at net.dandielo.citizens.trader.CitizensTrader.onEnable(CitizensTrader.java:87)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.loadPlugin(CraftServer.java:282)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.enablePlugins(CraftServer.java:264)
    at net.minecraft.server.v1_5_R2.MinecraftServer.j(MinecraftServer.java:303)
    at net.minecraft.server.v1_5_R2.MinecraftServer.e(MinecraftServer.java:282)
    at net.minecraft.server.v1_5_R2.MinecraftServer.a(MinecraftServer.java:242)
    at net.minecraft.server.v1_5_R2.DedicatedServer.init(DedicatedServer.java:150)
    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:381)
    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)

Ps: I am using the latest dev build #188

**Comment by Dandielo** [comment]
going to look into this but it looks like, that there is a bug in your config

**Comment by mozartripper** [comment]
Here is my config I haven't changed anything since it was generated by the plugin.
http://pastebin.com/udrqYC4L
I placed
    cititrader:
        convert: true
after
    amounts-return: 
      item: '35:14'
ps: Sorry I hit the close button.

**Comment by Dandielo** [comment]
you have probably added that config node one layer to high, so it was assigned to the "inventory-navigation" node.

Better is to set the node on the beginning, then it's easier to get it working :)

```
trader: 
  cititrader:
    convert: true
  patterns:
    file: 'patterns.yml'
    default: ''
```

**Comment by mozartripper** [comment]
I used this:
  cititrader:
    convert: true
instead of this
    cititrader:
        convert: true
(removed 2 space in front of cititraders and 4 from convert) and it worked. Only down side is it didn't convert the prices so all items are now 0$. They all look like this:
- 339 s:-1 d:0 a:1 !pat !pm
- 298 s:-1 d:0 a:1 c:160^101^64 !pat !pm
  ps: What do the letters means ( I cant seem to find a list with a description of them).
  Ty for the support :P

**Comment by Dandielo** [comment]
This will be described in the patterns section, going to try to fix this thing with prices
