### ISSUE TITLE
Java error in 1.5.1

### ISSUE THREAD

**Issue by Danton1983** [Dandielo/DtlCitizensTrader#67]
2013-04-07 15:08:44 [SEVERE] Error occurred while enabling DtlCitizensTrader v2.5.0 Alpha (Is it up to date?)
java.lang.NoClassDefFoundError: net/aufdemrand/denizen/utilities/arguments/Item
    at net.dandielo.citizens.trader.denizen.AbstractDenizenCommand.initializeDenizenCommands(AbstractDenizenCommand.java:27)
    at net.dandielo.citizens.trader.CitizensTrader.initializeDenizens(CitizensTrader.java:195)
    at net.dandielo.citizens.trader.CitizensTrader.onEnable(CitizensTrader.java:162)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.loadPlugin(CraftServer.java:282)
    at org.bukkit.craftbukkit.v1_5_R2.CraftServer.enablePlugins(CraftServer.java:264)
    at net.minecraft.server.v1_5_R2.MinecraftServer.j(MinecraftServer.java:303)
    at net.minecraft.server.v1_5_R2.MinecraftServer.e(MinecraftServer.java:282)
    at net.minecraft.server.v1_5_R2.MinecraftServer.a(MinecraftServer.java:242)
    at net.minecraft.server.v1_5_R2.DedicatedServer.init(DedicatedServer.java:150)
    at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:381)
    at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.denizen.utilities.arguments.Item
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:80)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
    ... 14 more

**Comment by Dandielo** [comment]
plz Denizen (build), Trader (build) and Citizens Version! :D

**Comment by dddeeefff** [comment]
I think we got this too, but am not sure... I've been waiting on a build for 1.5.1 before re-adding traders to the server.

I'll see if I can get a build number tomorrow, it'll be the latest version

edit: Oh and it happened on server startup

**Comment by Dandielo** [comment]
I would like rather know the denizen version you are using, because it's a denizen integration error

**Comment by dddeeefff** [comment]
Just downloaded the latest dev builds of Citizens2 (#784) and Denizen (#992) and got the below error, which, at a glance, looks to be the same as the one above.

```10:44:39 [INFO] [DtlCitizensTrader] Enabling DtlCitizensTrader v2.5.0 Alpha
10:44:39 [INFO] [DtlCitizensTrader] Loading locale
10:44:39 [INFO] [DtlCitizensTrader] Loading bank accounts
10:44:39 [SEVERE] [DtlCitizensTrader] player_accounts.yml not found!
10:44:39 [INFO] [DtlCitizensTrader] loading patterns
10:44:39 [INFO] [DtlCitizensTrader] Using Craftconomy3 plugin
10:44:39 [INFO] [DtlCitizensTrader] Hooked into Denizen v0.8-prerelease
10:44:39 [INFO] [DtlCitizensTrader] Registering commands... 
10:44:39 [SEVERE] Error occurred while enabling DtlCitizensTrader v2.5.0 Alpha (Is it up to date?)
java.lang.NoClassDefFoundError: net/aufdemrand/denizen/utilities/arguments/Item
        at net.dandielo.citizens.trader.denizen.AbstractDenizenCommand.initializeDenizenCommands(AbstractDenizenCommand.java:27)
        at net.dandielo.citizens.trader.CitizensTrader.initializeDenizens(CitizensTrader.java:195)
        at net.dandielo.citizens.trader.CitizensTrader.onEnable(CitizensTrader.java:162)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:217)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:457)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:383)
        at org.bukkit.craftbukkit.v1_5_R2.CraftServer.loadPlugin(CraftServer.java:305)
        at org.bukkit.craftbukkit.v1_5_R2.CraftServer.enablePlugins(CraftServer.java:287)
        at net.minecraft.server.v1_5_R2.MinecraftServer.j(MinecraftServer.java:309)
        at net.minecraft.server.v1_5_R2.MinecraftServer.e(MinecraftServer.java:288)
        at net.minecraft.server.v1_5_R2.MinecraftServer.a(MinecraftServer.java:248)
        at net.minecraft.server.v1_5_R2.DedicatedServer.init(DedicatedServer.java:154)
        at net.minecraft.server.v1_5_R2.MinecraftServer.run(MinecraftServer.java:387)
        at net.minecraft.server.v1_5_R2.ThreadServerApplication.run(SourceFile:573)
Caused by: java.lang.ClassNotFoundException: net.aufdemrand.denizen.utilities.arguments.Item
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at org.bukkit.plugin.java.PluginClassLoader.findClass0(PluginClassLoader.java:87)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:53)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:423)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:356)
        ... 14 more

```

```

**Comment by Dandielo** [comment]
Awesome, they change another time denizen commands initialization <3

**Comment by Dandielo** [comment]
latest build should have it fixed :)
